version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: todo_management
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopassword
    ports:
      - "15501:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todo_management"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: